services:
  - type: web
    name: solvence-agency
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://solvencetech:***@cluster0.vdzarsz.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: solvence_super_secret_key_2026_production
    plan: free
