services:
  - type: web
    name: solvence-agency
    env: node
    rootDir: backend
    buildCommand: cd ../frontend && npm install && npx vite build && cp -r dist/* ../backend/public/ && cd ../backend && npm install
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://solvencetech:Solvence123456@cluster0.vdzarsz.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: solvence_super_secret_key_2026_production
    plan: free
